FROM ubuntu:latest
#FROM wouterds/rpi-jenkins:latest
#FROM jenkins/jenkins:lts
#RUN apt-get update
#RUN apt-get install -y \
#    curl \
#    cvs \
#    git \
#    nginx
#WORKDIR ./product-register
CMD ["bash"]
