version: 2.1
jobs:
  build:
    # environment:
    #   DEBIAN_FRONTEND: noninteractive
    docker: 
      - image: ubuntu:latest # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: apt-get update
      - run: apt-get install -y wget sudo gnupg vim
      - run: sudo apt-get update
      - run: export DEBIAN_FRONTEND=noninteractive
      #   name: Setup Path
      #   command: |
      #     echo 'export DEBIAN_FRONTEND=noninteractive' >> $BASH_ENV
      - run: DEBIAN_FRONTEND="noninteractive" sudo apt-get install -y php
      # - run: sudo apt-get install -y php-mbstring
      # - run: sudo apt-get install -y php-xml
      - run: php -v